name: SIA CID parser
version: dev
slug: siacid
description: SIA CID parser addon for home assistant
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
legacy: true
init: false
ports:
  10006/tcp: 10006
ports_description:
  10006/tcp: "SIA: forward this port in your router"
services:
  - 'mqtt:need'
hassio_api: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
#  server:
#    host: str
